-- Dimensão analítica: recorte não-identificável de customer_profile, sem PII
-- (nome, documento, e-mail, data de nascimento exata). Uso em BI/agregações.
select
    customer_id,
    user_pseudo_id,
    gender,
    age,
    language_preference,
    email_opt_in,
    sms_opt_in,
    push_opt_in,
    whatsapp_opt_in,
    email_verified,
    has_verified_phone,
    location_country,
    location_region,
    location_city,
    preferred_device_category,
    viewed_top_category,
    viewed_top_brand,
    ga4_total_events,
    ga4_distinct_days_active,
    ga4_first_seen_at,
    ga4_last_seen_at,
    total_orders,
    total_revenue,
    avg_order_value,
    first_purchase_at,
    last_purchase_at,
    recency_days,
    total_refunds,
    total_refund_value,
    net_revenue,
    favorite_category,
    favorite_brand
from {{ ref('customer_profile') }}
